name: Lint Markdown

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Lint and auto-fix Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
          fix: true
        continue-on-error: true

      - name: Commit and push changes if any fixes were made
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m 'chore: auto-fix markdownlint issues [skip ci]'
            git push
          fi
